### ISSUE TITLE
script broken, 

### ISSUE THREAD

**Issue by frazz1234** [Guccirp2/qtarget-duty#1]
Nohting work! the script is not made for qtarget...!

**Comment by Guccirp2** [comment]
Totally forgot to add the qtarget exports when I uploaded. Download the updated version and check the client.lua

**Comment by frazz1234** [comment]
thanks il try tonight!

**Comment by frazz1234** [comment]
and still not working. you forgot a end a the end of main client.

**Comment by Guccirp2** [comment]
You are right. Fixed
